#!/bin/bash

#----------------------------------------------------------------------
# [EN] Main Snoopix Script
# [ES] Script principal del sistema Snoopix.
#----------------------------------------------------------------------
# Copyright © 2018 by Peke Soft, Ltd. Licensed under CC-NC-SA
#   v.1.0.0 Oct 2020 By ChuxMan. (chuxman@pekesoft.com)
#----------------------------------------------------------------------
# Snoopix is located into 2 paths:
#     /opt/snoopix --> Local instance
#     /srv/snoopix --> Server remote instance.
# For local instances, /srv/snoopix points to /opt/snoopix until
# remote instance will be applied. We asume to use /srv/snoopix as default.
# More info at snoopix-setup.
#----------------------------------------------------------------------

# First of all, we need to load the Snoopix framework
if [ -f /srv/snoopix/lib/snoopix-framework ]; then
  . /srv/snoopix/lib/snoopix-framework
else
  #TODO: Cambiar esto por la autoejecución del script de setup después de preguntar al usuario.
  # Little portion of ANSI colors constants defined in snoopix-framework
  Red='\033[0;31m'; Green='\033[0;32m'; NC='\033[0m'

  echo -e "${Red}[ERROR]${NC} Debes instalar previamente el framework de snoopix."
  echo -e "Ejecuta ${Green}./snoopix-setup${NC}"
  exit 0
fi

# INTERACTIVE=True
# ASK_TO_REBOOT=0
# BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
# CONFIG=/boot/config.txt
# MyPath=./

#TODO: Agregar línea de comandos para autoejecución jerárquica.

# Menú principal de Snoopix. Portal de acceso a toda la funcionalidad.
MenuTitle="Menú Principal"
SetMenuItems '
"0 Status"        "| Monitor del estado del Sistema Operativo y servicios"
"1 Información"   "| Muestra toda la información del Sistema Operativo y el hardware."
"2 Setup"         "| Configura tanto los aspectos básicos del Sistema Operativo como de Snoopix."
"3 Sistema"       "| Administración y mantenimiento del Sistema Operativo y los servicios instalados."
"4 Servicios"     "| Instalador y Administrador de servicios."
"5 Backup"        "| Creación y mantenimiento de copias de seguridad."
"6 Limpieza"      "| Limpieza de archivos obsoletos y del Sistema Operativo."
"7 Seguridad"     "| Configuración y mantenimiento de la seguridad del Sistema Operativo."
"8 Herramientas"  "| Utilidades y herramientas del Sistema Operativo."
"9 Asistentes"    "| Robots automatizados para la creación, configuración y automantenimiento de servicios."
"D Desktop"       "| Utilidades para Agregar, Eliminar y Administrar la gestión gráfica de Usuario."
"U Update"        "| Actualiza tanto el sistema de Snoopix como el Sistema Operativo y procede a un Clean Up."'

while true; do
  ShowMenu
  if [ $Return -eq 1 ]; then
    # El usuario ha pusado en salir
    clear 
    exit 0
  elif [ $Return -eq 0 ]; then
    case "$MenuChoice" in
      0\ *) source /srv/snoopix/status/@status ;;
      1\ *) source /srv/snoopix/info/@info ;;
      2\ *) source /srv/snoopix/setup/@setup ;;
      3\ *) source /srv/snoopix/system/@system ;;
      4\ *) source /srv/snoopix/services/@services ;;
      5\ *) source /srv/snoopix/backup/@backup ;;
      6\ *) source /srv/snoopix/cleanup/@cleanup ;;
      7\ *) source /srv/snoopix/security/@security ;;
      8\ *) source /srv/snoopix/tools/@tools ;;
      9\ *) source /srv/snoopix/wizards/@wizards ;;
      D\ *) source /srv/snoopix/desktop/@desktop ;;
      U\ *) source /srv/snoopix/update/@update ;;
      *) whiptail --msgbox "[ERROR] Imposible reconocer la selección" 20 60 1 ;;
    esac || whiptail --msgbox "[ERROR] Hay un error tratando de cargar el menú, posiblemente no se encuentra disponible. Actualiza Snoopix. $FUN" 20 60 1
  else
    exit 1
  fi
done