#!/bin/bash

#----------------------------------------------------------------------
# Main Snoopix Script
#----------------------------------------------------------------------
# Copyright © 2018 by Peke Soft, Ltd. JAN-2018.
#----------------------------------------------------------------------

# First of all, we need to load the Snoopix framework
if [ -f /srv/snoopix/lib/snoopix-framework ]; then
  . /srv/snoopix/lib/snoopix-framework
else
  # Little portion of ANSI colors constants defined in snoopix-framework
  Red='\033[0;31m'
  Green='\033[0;32m'
  NC='\033[0m'

  echo -e "${Red}[ERROR]${NC} Debes instalar previamente el framework de snoopix."
  echo -e "Ejecuta ${Green}./snoopix-setup.sh${NC}"
  exit 0
fi

INTERACTIVE=True
ASK_TO_REBOOT=0
BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
CONFIG=/boot/config.txt
MyPath=./

#
# Interactive use loop
#
. ./lib/snoopix-calcs

# set -x
while true; do
  FUN=$(whiptail --title "Menú Principal - Snoopix" --menu \
  "                              _
  ___ _ __   ___   ___  _ __ (_)_  __
 / __| '_ \ / _ \ / _ \| '_ \| \ \/ /
 \__ \ | | | (_) | (_) | |_) | |>  <
 |___/_| |_|\___/ \___/| .__/|_/_/\_\
                       |_|
" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT \
    --cancel-button Salir --ok-button Seleccionar \
    "1 Sistema" "Administración y mantenimiento del Sistema Operativo" \
    "2 Servicios" "Administrador de servicios" \
    "3 Backup" "Servidor moderno basado en javascript" \
    "4 Varnish" "Caché acelerador de carga" \
    3>&1 1>&2 2>&3)
  RET=$?
  if [ $RET -eq 1 ]; then
    exit 0
  elif [ $RET -eq 0 ]; then
    case "$FUN" in
      1\ *) source ./services/snoopix-services ;;
      2\ *) source ./wizards/snoopix-web ;;
      3\ *) do_boot_behaviour ;;
      4\ *) do_internationalisation_menu ;;
      *) whiptail --msgbox "[ERROR] Imposible reconocer la selección" 20 60 1 ;;
    esac || whiptail --msgbox "[ERROR] Hay un error tratando de cargar el servicio $FUN" 20 60 1
  else
    exit 1
  fi
  # set +x
done
