#!/bin/bash

#----------------------------------------------------------------------
# [EN] Main Snoopix Script
# [ES] Script principal del sistema Snoopix.
#----------------------------------------------------------------------
# Copyright © 2018 by Peke Soft, Ltd. Licensed under CC-NC-SA
#   v.1.0.0 Oct 2020 By ChuxMan. (chuxman@pekesoft.com)
#----------------------------------------------------------------------
# Snoopix is located into 2 paths:
#     /opt/snoopix --> Local instance
#     /srv/snoopix --> Server remote instance.
# For local instances, /srv/snoopix points to /opt/snoopix until
# remote instance will be applied. We asume to use /srv/snoopix as default.
# More info at snoopix-setup.
#----------------------------------------------------------------------

# First of all, we need to load the Snoopix framework
if [ -f /srv/snoopix/lib/snoopix-framework ]; then
  . /srv/snoopix/lib/snoopix-framework
else
  # Little portion of ANSI colors constants defined in snoopix-framework
  Red='\033[0;31m'; Green='\033[0;32m'; NC='\033[0m'

  echo -e "${Red}[ERROR]${NC} Debes instalar previamente el framework de snoopix."
  echo -e "Ejecuta ${Green}./snoopix-setup${NC}"
  exit 0
fi

# INTERACTIVE=True
# ASK_TO_REBOOT=0
# BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
# CONFIG=/boot/config.txt
# MyPath=./

#TODO: Agregar línea de comandos para autoejecución jerárquica.

# Depuración de menús.
# PrintInfo "MainMenu" "Cargando menú principal. Height: $ScreenHeight | Width: $ScreenWidth | MenuHeight: $MenuHeight"
# Pause 2

MenuTitle="Menú Principal"
SetMenuItems '
"0 Status" "| Monitor del estado del sistema y servicios"
"1 Información" "| Muestra toda la información del sistema y el hardware."
"2 Setup" "| Configura tanto los aspectos básicos del sistema como de Snoopix."
"3 Sistema" "| Administración y mantenimiento del Sistema Operativo y los servicios instalados."
"4 Servicios" "| Instalador y Administrador de servicios."
"5 Backup" "| Creación y mantenimiento de copias de seguridad."
"6 Limpieza" "| Limpieza de archivos obsoletos y del sistema operativo."
"7 Seguridad" "| Configuración y mantenimiento de la seguridad del sistema."
"8 Herramientas" "| Utilidades y herramientas del sistema."
"9 Asistentes" "| Robots automatizados para la creación, configuración y automantenimiento de servicios."
"D Desktop" "| Utilidades para Agregar, Eliminar y Administrar la gestión gráfica de Usuario."
"U Update" "| Actualiza tanto el sistema de Snoopix como el Sistema Operativo y procede a un Clean Up."'

while true; do
  ShowMenu
  # MenuChoice=$(whiptail --title "Menú Principal - Snoopix" --backtitle "$DebugInfo" \
  #   --menu "$LogoInfo \n\n\n\n                                 Bienvenid@ al menú principal. Elije una opción:\n\n" $ScreenHeight $ScreenWidth $MenuHeight \
  #   --cancel-button "Salir" --ok-button "Seleccionar" \
  #   "0 Status" "| Monitor del estado del sistema y servicios" \
  #   "1 Información" "| Muestra toda la información del sistema y el hardware." \
  #   "2 Setup" "| Configura tanto los aspectos básicos del sistema como de Snoopix." \
  #   "3 Sistema" "| Administración y mantenimiento del Sistema Operativo y los servicios instalados." \
  #   "4 Servicios" "| Instalador y Administrador de servicios." \
  #   "5 Backup" "| Creación y mantenimiento de copias de seguridad." \
  #   "6 Limpieza" "| Limpieza de archivos obsoletos y del sistema operativo." \
  #   "7 Seguridad" "| Configuración y mantenimiento de la seguridad del sistema." \
  #   "8 Herramientas" "| Utilidades y herramientas del sistema." \
  #   "9 Asistentes" "| Robots automatizados para la creación, configuración y automantenimiento de servicios." \
  #   "D Desktop" "| Utilidades para Agregar, Eliminar y Administrar la gestión gráfica de Usuario." \
  #   "U Update" "| Actualiza tanto el sistema de Snoopix como el Sistema Operativo y procede a un Clean Up." \
  #   3>&1 1>&2 2>&3)
  # Return=$?
  if [ $Return -eq 1 ]; then
    clear 
    exit 0
  elif [ $Return -eq 0 ]; then
    case "$MenuChoice" in
      0\ *) source ./status/@status ;;
      1\ *) source ./info/@info ;;
      2\ *) source ./setup/@setup ;;
      3\ *) source ./system/@system ;;
      4\ *) source ./services/@services ;;
      5\ *) source ./backup/@backup ;;
      6\ *) source ./cleanup/@cleanup ;;
      7\ *) source ./security/@security ;;
      8\ *) source ./tools/@tools ;;
      9\ *) source ./wizards/@wizards ;;
      D\ *) source ./desktop/@desktop ;;
      U\ *) source ./update/@update ;;
      *) whiptail --msgbox "[ERROR] Imposible reconocer la selección" 20 60 1 ;;
    esac || whiptail --msgbox "[ERROR] Hay un error tratando de cargar el menú, posiblemente no se encuentra disponible. Actualiza Snoopix. $FUN" 20 60 1
  else
    exit 1
  fi
done