#!/bin/bash

#----------------------------------------------------------------------
# [EN] Main Snoopix framework script
# [ES] Script principal del framework de Snoopix.
#----------------------------------------------------------------------
# Copyright © 2018 by Peke Soft, Ltd. Licensed under GPL 3.0
#----------------------------------------------------------------------
# Coded & Designed by ChuxMan (chuxman@pekesoft.com)
#----------------------------------------------------------------------

# Check if there's a previous framework loaded
if [ $Snoopix -eq 1 ]; then
  return
fi

#----------------------------------------------------------------------
# Screen Calcs for Whiptail. Based on raspi-config
#----------------------------------------------------------------------
CalcScreen() {

  # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
  # output from tput. However in this case, tput detects neither stdout or
  # stderr is a tty and so only gives default 80, 24 values

  ScreenHeight=17
  ScreenWidth=$(tput cols)

  if [ -z "$ScreenWidth" ] || [ "$ScreenWidth" -lt 60 ]; then
    ScreenWidth=80
  fi
  if [ "$ScreenWidth" -gt 178 ]; then
    ScreenWidth=120
  fi

  MenuHeight=$(($ScreenWidth-7))

}

#----------------------------------------------------------------------
# ANSI colors constants for terminal
# Based on https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
#----------------------------------------------------------------------
AnsiColors() {

  #----------------------------------------------------------------------
  # Black        0;30     Dark Gray     1;30
  # Red          0;31     Light Red     1;31
  # Green        0;32     Light Green   1;32
  # Brown/Orange 0;33     Yellow        1;33
  # Blue         0;34     Light Blue    1;34
  # Purple       0;35     Light Purple  1;35
  # Cyan         0;36     Light Cyan    1;36
  # Light Gray   0;37     White         1;37
  #----------------------------------------------------------------------
  # And then use them like this in your script:

  #      .---------- constant part!
  #      vvvv vvvv-- the code from above
  # Red='\033[0;31m'

  # printf "I ${Red}love${NoColor} Snoopix\n"

  # if you are using the echo command, be sure to use the -e flag to allow backslash escapes.
  # echo -e "I ${Red}love${NC} Snoopix"
  #----------------------------------------------------------------------

  Black='\033[0;30m'
  Red='\033[0;31m'
  Green='\033[0;32m'
  Orange='\033[0;33m'
  Brown=$Orange
  Blue='\033[0;34m'
  Purple='\033[0;35m'
  Cyan='\033[0;36m'
  LightGray='\033[0;37m'

  DarkGray='\033[1;30m'
  LightRed='\033[1;31m'
  LightGreen='\033[1;32m'
  Yellow='\033[1;33m'
  LightBlue='\033[1;34m'
  LightPurple='\033[1;35m'
  LightCyan='\033[1;36m'
  White='\033[1;37m'

  NoColor='\033[0m'
  NC=$NoColor
}

#----------------------------------------------------------------------
# Get System Version and distribution
# Based on https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
#----------------------------------------------------------------------
SystemVersion() {

  # Kernel Version, for example: 4.15.0-10-generic
  KernelVersion=$(uname -r)

  # Machine name, for example: MyComputer
  MachineName=$(uname -n)

  # Architecture, for example: x86_64
  Architecture=$(uname -m)

  # System Type, for example: darwin, linux
  SystemType=$(uname -s)

  # If SystemType is not darwin, then get release variables.
  if [ ! $SystemType -eq "darwin"]; then

    # Include system release.
    . /etc/os-release



  fi
}

# Function to create a checksum file
CreateChecksum () {

  printf "${LightGreen}[INFO]${NoColor} Creando fichero de comprobación: ${White}$1.md5${NoColor}\n\n"

  # Create Checksum file
  md5sum "$1" > "${1}.md5"

  CheckChecksum "$1"
}

CreateChecksumFile () {

  PrintInfo "Creando fichero de checksum global:" "@Checksum.md5"

  # Remove previous checksums
  rm "@Checksum.md5"

  # Create a new checksum.
  cat *.md5 > @Checksum.md5

  CheckChecksum "@Checksum"
}

CheckChecksum () {

  PrintInfo "Comprobando fichero de checksum:" "${1}.md5"

  # Check if checksum is right
  md5sum -c "${1}.md5"
}

PrintInfo () {
  if [ ! -z "$2" ]; then
    SubText="$1 ${White}$2${NoColor}"
  else
    SubText="$1"
  fi

  printf "\n${LightGreen}[INFO]${NoColor} $SubText\n\n"
}

#----------------------------------------------------------------------
# Main Init Script
#----------------------------------------------------------------------

# Load Screen Sizes
CalcScreen

# Set ANSI colors
AnsiColors

# Get System version
SystemVersion

# Set Global variable to avoid recursive loads.
Snoopix=1
