#!/bin/bash

#----------------------------------------------------------------------
# Script para la instalación y mantenimiento de Nginx.
#----------------------------------------------------------------------
# Copyright © 2018 by Peke Soft, Ltd. JAN-2018.
#----------------------------------------------------------------------

# Cargamos el sistema de inicialización del framework de Snoopix.
# TODO
