#!/bin/sh

#----------------------------------------------------------------------
# Script para la instalación y mantenimiento de Nginx.
#----------------------------------------------------------------------
# Copyright © 2018 by Peke Soft, Ltd. 03-01-2017.
#----------------------------------------------------------------------

# Cargamos el sistema de inicialización del framework de Snoopix.
# TODO
