#!/bin/bash

# Script para crear un servidor de centralización de Snoopix para
# simplificar y automatizar las instalaciones corporativas mediante samba.
# Además crea las estructuras de red.

# 
CreateNet() {

}
