#!/bin/sh

PATH=".."
. ../lib/snoopix-init

#
# Interactive use loop
#
# calc_wt_size
# set -x
while true; do
  FUN=$(whiptail --title "Asistente de instalación de Servicios Web" --checklist \
"\nA continuación se muestran todos los servicios web disponibles. Los servicios marcados se instalarán y los desmarcados se desistalarán si estaban previamente instalados." 20 78 4 --cancel-button Volver --ok-button Instalar \
"1 Apache" "Servidor robusto, estable, muy popular y extenido" ON \
"2 Nginx" "Servidor más liviano y óptimo" ON \
"3 Node.js" "Servidor moderno basado en javascript" ON \
"4 Varnish" "Caché acelerador de carga" ON \
    3>&1 1>&2 2>&3)
  RET=$?
  if [ $RET -eq 1 ]; then
    return
  elif [ $RET -eq 0 ]; then
    case "$FUN" in
      1\ *) source ./services/web/snoopix-apache ;;
      2\ *) do_change_pass ;;
      3\ *) do_boot_behaviour ;;
      4\ *) do_internationalisation_menu ;;
      *) whiptail --msgbox "[ERROR] Imposible reconocer la selección" 20 60 1 ;;
    esac || whiptail --msgbox "Hay un error tratando de cargar el servicio $FUN" 20 60 1
  else
    exit 1
  fi
  # set +x
done
